/**
 * @fileoverview Payment initiation API methods (LiqPay integration).
 *
 * All three methods return a signed LiqPay payload (`data` + `signature`)
 * that the frontend forwards to the LiqPay hosted checkout via a form POST.
 * The actual payment confirmation is handled server-to-server by the backend
 * webhook at `POST /api/payments/callback`.
 *
 * @module services/api/payments
 */

import config from '../../config';
import { PaymentInitiateResponse, ApiResponse } from '../../types';
import { ApiClient } from './client';

/** Envelope shape returned by the payment initiation endpoints. */
interface PaymentInitiateEnvelope extends ApiResponse<PaymentInitiateResponse> {
  data: PaymentInitiateResponse;
}

/**
 * Creates payment-initiation methods bound to the given HTTP client.
 *
 * @param client - Shared API transport client.
 * @returns Object containing all payment API methods.
 * @example
 * ```ts
 * const { initiateCartPayment } = createPaymentsMethods(client);
 * const payment = await initiateCartPayment([1, 2, 3]);
 * submitLiqPayForm(payment.data, payment.signature);
 * ```
 */
export function createPaymentsMethods(client: ApiClient) {
  return {
    /**
     * Initiates a LiqPay payment for a single catalog product.
     *
     * @param productId - ID of the product to purchase.
     * @returns Signed LiqPay payload to submit to the checkout form.
     * @throws {ApiError} 404 - Product not found or hidden.
     * @throws {ApiError} 409 - Product already purchased by this user.
     * @example
     * ```ts
     * const payment = await apiService.initiateProductPayment(42);
     * submitLiqPayForm(payment.data, payment.signature);
     * ```
     */
    async initiateProductPayment(productId: number): Promise<PaymentInitiateResponse> {
      const response = await client.post<PaymentInitiateEnvelope>(
        config.endpoints.payments.initiateProduct(productId),
        {},
      );
      return response.data;
    },

    /**
     * Initiates a LiqPay payment for a personal order.
     *
     * The order must be in `'accepted'` status and have a price set by an admin.
     *
     * @param orderId - ID of the personal order to pay for.
     * @returns Signed LiqPay payload to submit to the checkout form.
     * @throws {ApiError} 404 - Order not found.
     * @throws {ApiError} 403 - Order belongs to another user.
     * @throws {ApiError} 400 - Order not awaiting payment or has no price.
     * @example
     * ```ts
     * const payment = await apiService.initiateOrderPayment(7);
     * submitLiqPayForm(payment.data, payment.signature);
     * ```
     */
    async initiateOrderPayment(orderId: number): Promise<PaymentInitiateResponse> {
      const response = await client.post<PaymentInitiateEnvelope>(
        config.endpoints.payments.initiateOrder(orderId),
        {},
      );
      return response.data;
    },

    /**
     * Initiates a single LiqPay payment for all products currently in the cart.
     *
     * The total amount is the sum of all product prices.  On a successful
     * payment, the backend webhook records all products as purchased.
     *
     * @param productIds - Array of product IDs in the cart.
     * @returns Signed LiqPay payload to submit to the checkout form.
     * @throws {ApiError} 400 - `productIds` is empty or invalid.
     * @throws {ApiError} 404 - One or more products not found or hidden.
     * @throws {ApiError} 409 - One or more products already purchased.
     * @example
     * ```ts
     * const payment = await apiService.initiateCartPayment([1, 2, 3]);
     * submitLiqPayForm(payment.data, payment.signature);
     * ```
     */
    /**
     * Verifies a completed LiqPay payment and records the purchase server-side.
     *
     * Used as a fallback when LiqPay's server-to-server webhook cannot reach the
     * local development server.  The `orderId` must have been generated by one of
     * the initiation endpoints and must encode the authenticated user's ID.
     *
     * @param orderId - The LiqPay order_id stored in localStorage before redirect.
     * @returns Resolves on success; throws `ApiError` on auth or validation failure.
     * @example
     * ```ts
     * const orderId = getPendingOrderId();
     * if (orderId) {
     *   await apiService.verifyPayment(orderId);
     *   clearPendingOrderId();
     * }
     * ```
     */
    async verifyPayment(orderId: string): Promise<void> {
      await client.post<ApiResponse<void>>(config.endpoints.payments.verify, { orderId });
    },

    /**
     * Initiates a single LiqPay payment for all products currently in the cart.
     *
     * Pass `guestToken` when the buyer is an unregistered guest who has verified
     * their email.  Omit it (or pass `undefined`) for authenticated users.
     *
     * @param productIds - Array of product IDs in the cart.
     * @param guestToken - Optional short-lived guest JWT from `confirmGuestEmail`.
     * @returns Signed LiqPay payload to submit to the checkout form.
     * @throws {ApiError} 400 - `productIds` is empty or invalid.
     * @throws {ApiError} 404 - One or more products not found or hidden.
     * @throws {ApiError} 409 - One or more products already purchased (authenticated only).
     * @example
     * ```ts
     * // Authenticated user
     * const payment = await apiService.initiateCartPayment([1, 2, 3]);
     *
     * // Guest shopper
     * const payment = await apiService.initiateCartPayment([1, 2, 3], guestToken);
     *
     * submitLiqPayForm(payment.data, payment.signature);
     * ```
     */
    async initiateCartPayment(productIds: number[], guestToken?: string): Promise<PaymentInitiateResponse> {
      const response = guestToken
        ? await client.postWithCustomAuth<PaymentInitiateEnvelope>(
            config.endpoints.payments.initiateCart,
            { productIds },
            guestToken,
          )
        : await client.post<PaymentInitiateEnvelope>(
            config.endpoints.payments.initiateCart,
            { productIds },
          );
      return response.data;
    },

    /**
     * Fallback payment verification for guest shoppers on localhost development.
     *
     * Called by `PaymentResultPage` when a guest order's `order_id` is present in
     * localStorage.  Passes the guest JWT so the backend can verify ownership.
     *
     * @param orderId    - The LiqPay order_id stored before the redirect.
     * @param guestToken - The guest JWT stored before the redirect.
     * @returns Resolves on success; throws `ApiError` on auth or validation failure.
     * @example
     * ```ts
     * const orderId = getPendingOrderId();
     * const token   = getGuestPaymentToken();
     * if (orderId && token) {
     *   await apiService.verifyGuestPayment(orderId, token);
     * }
     * ```
     */
    async verifyGuestPayment(orderId: string, guestToken: string): Promise<void> {
      await client.postWithCustomAuth<ApiResponse<void>>(
        config.endpoints.payments.verify,
        { orderId },
        guestToken,
      );
    },
  };
}
